# network analysis

```{r packages_network, warning=FALSE, message=FALSE}
#install.packages("data.table")
#install.packages("igraph")

# ライブラリコマンドでの読み込みは毎回必要
library(tidyverse)
library(data.table)
library(igraph)
library(tidygraph)
library(ggraph)

#getwd() # 現在の作業ディレクトリを確認
#setwd("D:/Offline_folder/Tokai/Tokai_DataAnalysis/dataanalysis") # 作業ディレクトリの変更

```

## ネットワーク分析
人間関係、企業間の関係など、様々な分野で活用される、グラフ理論をベースとした分析手法。

```{r}
#ウイスキーデータの取得
whiskies<-data.table::fread("http://outreach.mathstat.strath.ac.uk/outreach/nessie/datasets/whiskies.txt",header=TRUE)

#各蒸留所間の相関係数を算出
cor.mat<-whiskies %>% 
  select(Body,Sweetness,Smoky,Medicinal,Tobacco,Honey,
         Spicy,Winey,Nutty,Malty,Fruity,Floral) %>% 
  t() %>% 
  cor()

#行名・列名を追加
colnames(cor.mat)<-whiskies$Distillery
rownames(cor.mat)<-whiskies$Distillery

cor.mat[upper.tri(cor.mat,diag=TRUE)]<-NA

#Long formatに変換して相関係数0.8以上に絞り込み
d<-cor.mat %>% 
  as.data.frame() %>% 
  mutate(distillerry1 = whiskies$Distillery) %>% 
  gather(key="distillerry2", value="cor",-distillerry1) %>% 
  select(distillerry1,distillerry2,cor) %>% 
  filter(!is.na(cor) & cor >=0.80)
```

```{r}
g<-tidygraph::as_tbl_graph(d,directed = FALSE)

g

#密度
g %>% igraph::graph.density()
#推移性
g %>% igraph::transitivity()
#相互性（無向グラフは1）
g %>% igraph::reciprocity()

#媒介中心性の追加
g1<- g %>%
  mutate(centrality=centrality_betweenness())

g1

#辺媒介中心性の追加
g2<-g %>% activate(edges) %>%
  mutate(importance = centrality_edge_betweenness())

g2

#コミュニティ検出
g3<-g %>% 
  mutate(community=as.factor(group_fast_greedy(weights=cor)))

g3
```

```{r}
g3 %>% 
  mutate(degree=degree(g3)) %>% 
  ggraph(layout="kk")+
  geom_edge_link(aes(width = cor),
                 alpha=0.8,
                 colour="lightgray")+　#エッジの追加
  scale_edge_width(range=c(0.1,1))+ #太さの調節
  geom_node_point(aes(colour=community,size=degree))+ #ノードの追加
  geom_node_text(aes(label=name),repel=TRUE)
```

##参考

下記の資料を参考にこの項目を作成しました。
-https://www.slideshare.net/MitsunoriSato/tokyor32-network-analysis-24442516  
-https://www.slideshare.net/kashitan/tidygraphggraph-ver-152368322  
-https://www.slideshare.net/kashitan/ss-238547900  
-https://qiita.com/saltcooky/items/4e55d97c5e86dfb208cd  
