--- 
title: "データ分析入門"
author: "野村　魁"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
# github-repo: (your-github)
# bookdown::render_book("index.Rmd", output_format = "bookdown::gitbook")
description: "This site is prepared for Introductory Data Analysis at Tokai University. "
---

このページは「データ分析入門A」(土曜日１限)およびB(土曜日2限)で使うコンテンツをまとめたものです。
東海大学政治経済学部の山本雅資先生の資料を基に修正を加えた資料となります。

# イントロダクション

## 講義の概要

本講義では、Rというプログラミング言語を用いて、社会・経済関連のデータについて、初歩的な分析することができるようになることを目指します。ビジネスにおける活用を例としたR言語の紹介については以下のリンクを参考にしてください。

[日経クロステック (2020)「統計解析に便利、R言語の基本を実践で理解する」](https://xtech.nikkei.com/atcl/learning/lecture/19/00110/00002/)

Rは無料で提供されており、RStudioと呼ばれるインターフェースと同時に用いることで初心者にも比較的直感的に利用できる非常に優れた分析ツールです。講義では、プログラミングが初めての学生を想定して、Rのインストールから丁寧に行います。その上で、データの集計方法、グラフ、地図等による可視化、統計的仮説検定などを実行する方法を学びます。

## 履修上の注意点

講義の性質上、30人程度の履修制限を設ける場合があります。また、履修者は以下の条件をすべて満たしていることが必要です。

1.  講義にノートパソコンを持ってくることができる（Mac or Windows)

2.  情報処理Iの単位を取得済みである

## 成績評価の基準および方法

講義内演習での理解度 (70%)及び最終課題 (30%)で評価します。

## 授業計画

-   詳細はシラバスを参照してください。
-   講義での進捗・理解度に応じて、内容は変更する可能性があります。

## 謝辞

このページの作成にあたっては多くのウェブサイトや先人の皆様のウェブ・SNSでのやりとりなどを参考にさせていただきました。たくさんありすぎてここに列挙することはできませんが、心より感謝申し上げます。
