#  Rmarkdownの使い方

## Rmarkdownを用いる理由

個人的にデータを分析して楽しむ?場合には特に問題になりませんが、将来、データ分析の結果を仕事で用いることになった場合、その再現性が重要になります。前の学期に作業したエクセルファイルをどうやって作成したか、ファイルそのものを見直しても全く思い出せない、という経験がある人が皆さんの中にもいるかもしれません。個人の学習としてはともかく、ビジネスでこのようなことがおこることは絶対に避けなければなりません。

一定の時間が経過した後も同じ結果を確実に再現できるためには当初の分析段階で適切に記録を残しておくことが重要です。分析過程の記録を残すための`package`として、`Rmarkdown`というものがあります。この`Rmarkdown`を使うことで作成者の記録がとりやすいだけでなく、後でこの記録をみる利用者にとってもわかりやす資料を作ることができます。

## Rmarkdownの使い方

最も簡単に`Rmarkdown`を使う方法は、`RStudio`のメニューから`New File`、`R Markdown`を選択し、htmlで出力することです。このやり方は講義で画面で説明します。

`Rmarkdown`を用いることで、htmlの途中に`R`のコードを簡単に含めることができます。このコードは単にコードを表示するだけでなく、htmlを作成するタイミングで実行して実行結果を含めることができます。このコードを含める部分をチャンクと言います。チャンクで使用できるオプションについては[こちら](https://teramonagi.hatenablog.com/entry/20130615/1371303616)を参考にしてください。


## 参考資料

さらに細かい設定などに興味のある人は以下のサイトを参照してください。

- [Rmarkdown入門 (by kazutan on web)](https://kazutan.github.io/kazutanR/Rmd_intro.html)
- [Rmarkdown入門 (by Jaehyun Song)](https://www.jaysong.net/tutorial/R/rmarkdown_intro.html/)
- [R Markdown クックブック](https://gedevan-aleksizde.github.io/rmarkdown-cookbook/)
